name: pamelameraz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49428
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfd'
    - '#dbaab2'
    - '#a36876'
    - '#715562'
    - '#421821'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
