name: Pamela Meraz
favicon: null
layout_spectrum: 0.89139
typography_spectrum: 0.2932
title: Pamela Meraz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010001'
    - '#82a482'
    - '#696760'
    - '#c2ccd2'
    - '#423f35'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
