name: pamelameraz
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49428
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbdbdd'
    - '#000000'
    - '#502f38'
    - '#7c5862'
    - '#dea29d'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
